# Generated by Django 5.1.2 on 2024-10-28 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('disaster_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('flood', 'Flood'), ('earthquake', 'Earthquake'), ('fire', 'Fire'), ('storm', 'Storm'), ('drought', 'Drought'), ('landslide', 'Landslide'), ('tsunami', 'Tsunami'), ('volcano', 'Volcano')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High'), (4, 'Severe'), (5, 'Critical')], validators=[django.core.validators.MinValueValidator(1)])),
                ('response', models.TextField()),
                ('reported_by', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'disasters',
            },
        ),
    ]
