# Generated by Django 5.1.2 on 2024-10-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('medical', 'Medical'), ('food', 'Food'), ('shelter', 'Shelter'), ('clothing', 'Clothing'), ('transport', 'Transport'), ('volunteers', 'Volunteers'), ('other', 'Other')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=150)),
                ('availability_status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
    ]
